USE `quanlydiemthi`;		

CREATE TABLE `HocSinh` (
    MaHS VARCHAR(20) PRIMARY KEY,
    TenHS VARCHAR(50),
    NgaySinh DATETIME,
    lop VARCHAR(20),
    gt VARCHAR(20)
);

CREATE TABLE MonHoc (
    MaMH VARCHAR(20) PRIMARY KEY,
    TenMH VARCHAR(50)
);

CREATE TABLE BangDiem (
    MaHS VARCHAR(20),
    MaMH VARCHAR(20),
    NgayKT DATETIME,
    PRIMARY KEY (MaHS , MaMH),
    FOREIGN KEY (MaHS)
        REFERENCES HocSinh (MaHS),
    FOREIGN KEY (MaMH)
        REFERENCES MonHoc (MaMH)
);
CREATE TABLE GiaoVien (
    MaGV VARCHAR(20),
    TenGV VARCHAR(20),
    SDT VARCHAR(10)
);

ALTER TABLE MonHoc ADD MaGV VARCHAR(20);
ALTER TABLE GiaoVien ADD PRIMARY KEY(MaGV);

ALTER TABLE MonHoc ADD CONSTRAINT FK_MaGV FOREIGN KEY (MaGV) REFERENCES  GiaoVien(MaGV);